// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0Lu-fio9ph3sTyYfUbdyCjrKhJYNVag',
    appId: '1:1006387415222:web:660c7d1057b62f8350be17',
    messagingSenderId: '1006387415222',
    projectId: 'dispositivos-7daf3',
    authDomain: 'dispositivos-7daf3.firebaseapp.com',
    storageBucket: 'dispositivos-7daf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPGVO9ZNm-VRwKR_i0F2i0X2v2cmY4I4',
    appId: '1:1006387415222:android:f52b7637d1b93b2450be17',
    messagingSenderId: '1006387415222',
    projectId: 'dispositivos-7daf3',
    storageBucket: 'dispositivos-7daf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0p4o729OPNq387xjpE8hg-3wIp9g9nvc',
    appId: '1:1006387415222:ios:8e71879da860db0550be17',
    messagingSenderId: '1006387415222',
    projectId: 'dispositivos-7daf3',
    storageBucket: 'dispositivos-7daf3.appspot.com',
    iosBundleId: 'com.example.weFixIt',
  );
}
